language: python
python:
  - "3.6"
addons:
  apt:
    packages:
    - cython
    - zlib1g-dev
    - perl
    - r-base
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
  - "$HOME/perl5"
sudo: false
install:
  - source ./install_dependencies.sh
  - pip3 install cython
  - python3 setup.py install
before_script:
  - pip3 install codecov
script:
  - coverage run setup.py test
after_success:
  - codecov
