sudo: required
services:
  - docker
install:
  - docker pull andrewjpage/albatradis
script:
  - docker run --rm -it andrewjpage/albatradis /bin/sh -c "git clone https://github.com/andrewjpage/albatradis.git && cd albatradis && python3 setup.py test"
