language: python
python:
  - "3.5"
  - "3.6"
sudo: false
addons:
  apt:
    packages:
    - cython
	- zlib1g-dev
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
install:
  - source ./install_dependencies.sh
  - pip3 install cython
  - python3 setup.py install
before_script:
  - pip3 install codecov
script:
  - coverage run setup.py test
after_success:
  - codecov